name: "Build workflow"

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRAD_USER: ${{ secrets.GRAD_USER }}
      GRAD_PASS: ${{ secrets.GRAD_PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "${{ secrets.ENV_CONTENT }}" > .env

      - name: Load environment variables
        run: |
          set -a
          source .env
          set -a

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
