name: "Deploy Docker Image to Azure VM workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'development'
        type: string
      service_name:
        description: 'Service Name'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Docker Image to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}

      - name: Deploy Specific Service
        run: |
          if [ "${{ inputs.environment }}" == "production" ]; then
            IP_ADDRESS=${{ secrets.PROD_AZURE_VM_IP }}
            COMPOSE_FILE="docker-compose.prod.yml"
          else
            IP_ADDRESS=${{ secrets.DEV_AZURE_VM_IP }}
            COMPOSE_FILE="docker-compose.dev.yml"
          fi

          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@$IP_ADDRESS << EOF
            echo "Entering infra directory"
            cd infra

            echo "Log in to Docker inside the VM"
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pull the latest image for a specific service"
            docker-compose -f $COMPOSE_FILE pull ${{ inputs.service_name }}
          
            echo "Recreate the specific service container"
            docker-compose -f $COMPOSE_FILE up -d --no-deps ${{ inputs.service_name }}
          
            echo "Remove unused resources"
            docker system prune --volumes -f
          
            echo "Logout from ghcr.io Docker registry"
            docker logout ghcr.io
          
            echo "Exiting the SSH session"
            exit
          EOF
