name: Deploy Docker Image to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key to login
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}

      - name: Deploy Docker Image to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.DEV_AZURE_VM_IP }} << 'EOF'
            echo "test command"
            touch test.txt
            echo "test" >> test.txt
            echo "Exiting the SSH session"
            exit
          EOF
