name: Deploy Docker Image to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key to login
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}

      - name: Deploy Docker Image to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
#            echo "Logging in to GitHub Container Registry"
#            echo ${{ secrets.GRAD_PASS }} | docker login ghcr.io -u ${{ secrets.GRAD_USER }} --password-stdin
          
            echo "Pulling the latest Docker image from ghcr.io"
#            docker pull ghcr.io/YOUR_REPO/YOUR_IMAGE:latest
          
            echo "Stopping and removing old container (if running)"
#            docker stop my_container || true
#            docker rm my_container || true
          
            echo "Running the new container"
#            docker run -d --name my_container ghcr.io/YOUR_REPO/YOUR_IMAGE:latest
          
            echo "test command"
            touch test.txt
            echo "test" >> test.txt
          
            echo "Exiting the SSH session"
            exit
          EOF
