name: "Publish Docker images workflow"

on:
  workflow_call:
    inputs:
      workflow_file_path:
        required: true
        type: string
        description: "Path to the workflow file to run"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: snippetservices-group4
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ inputs.workflow_file_path }}
          build-args: |
            GRAD_USER=${{ secrets.GRAD_USER }}
            GRAD_PASS=${{ secrets.GRAD_PASS }}
